/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as ChatAssistantRouteImport } from './routes/chat-assistant'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChatAssistantSessionIdRouteImport } from './routes/chat-assistant.$sessionId'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiTrpcIngestSplatRouteImport } from './routes/api/trpc/ingest.$'
import { Route as ApiTrpcChatSplatRouteImport } from './routes/api/trpc/chat.$'

const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatAssistantRoute = ChatAssistantRouteImport.update({
  id: '/chat-assistant',
  path: '/chat-assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatAssistantSessionIdRoute = ChatAssistantSessionIdRouteImport.update({
  id: '/$sessionId',
  path: '/$sessionId',
  getParentRoute: () => ChatAssistantRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrpcIngestSplatRoute = ApiTrpcIngestSplatRouteImport.update({
  id: '/api/trpc/ingest/$',
  path: '/api/trpc/ingest/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrpcChatSplatRoute = ApiTrpcChatSplatRouteImport.update({
  id: '/api/trpc/chat/$',
  path: '/api/trpc/chat/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat-assistant': typeof ChatAssistantRouteWithChildren
  '/documents': typeof DocumentsRoute
  '/api/health': typeof ApiHealthRoute
  '/chat-assistant/$sessionId': typeof ChatAssistantSessionIdRoute
  '/api/trpc/chat/$': typeof ApiTrpcChatSplatRoute
  '/api/trpc/ingest/$': typeof ApiTrpcIngestSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat-assistant': typeof ChatAssistantRouteWithChildren
  '/documents': typeof DocumentsRoute
  '/api/health': typeof ApiHealthRoute
  '/chat-assistant/$sessionId': typeof ChatAssistantSessionIdRoute
  '/api/trpc/chat/$': typeof ApiTrpcChatSplatRoute
  '/api/trpc/ingest/$': typeof ApiTrpcIngestSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat-assistant': typeof ChatAssistantRouteWithChildren
  '/documents': typeof DocumentsRoute
  '/api/health': typeof ApiHealthRoute
  '/chat-assistant/$sessionId': typeof ChatAssistantSessionIdRoute
  '/api/trpc/chat/$': typeof ApiTrpcChatSplatRoute
  '/api/trpc/ingest/$': typeof ApiTrpcIngestSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat-assistant'
    | '/documents'
    | '/api/health'
    | '/chat-assistant/$sessionId'
    | '/api/trpc/chat/$'
    | '/api/trpc/ingest/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat-assistant'
    | '/documents'
    | '/api/health'
    | '/chat-assistant/$sessionId'
    | '/api/trpc/chat/$'
    | '/api/trpc/ingest/$'
  id:
    | '__root__'
    | '/'
    | '/chat-assistant'
    | '/documents'
    | '/api/health'
    | '/chat-assistant/$sessionId'
    | '/api/trpc/chat/$'
    | '/api/trpc/ingest/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatAssistantRoute: typeof ChatAssistantRouteWithChildren
  DocumentsRoute: typeof DocumentsRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiTrpcChatSplatRoute: typeof ApiTrpcChatSplatRoute
  ApiTrpcIngestSplatRoute: typeof ApiTrpcIngestSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat-assistant': {
      id: '/chat-assistant'
      path: '/chat-assistant'
      fullPath: '/chat-assistant'
      preLoaderRoute: typeof ChatAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat-assistant/$sessionId': {
      id: '/chat-assistant/$sessionId'
      path: '/$sessionId'
      fullPath: '/chat-assistant/$sessionId'
      preLoaderRoute: typeof ChatAssistantSessionIdRouteImport
      parentRoute: typeof ChatAssistantRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trpc/ingest/$': {
      id: '/api/trpc/ingest/$'
      path: '/api/trpc/ingest/$'
      fullPath: '/api/trpc/ingest/$'
      preLoaderRoute: typeof ApiTrpcIngestSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trpc/chat/$': {
      id: '/api/trpc/chat/$'
      path: '/api/trpc/chat/$'
      fullPath: '/api/trpc/chat/$'
      preLoaderRoute: typeof ApiTrpcChatSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ChatAssistantRouteChildren {
  ChatAssistantSessionIdRoute: typeof ChatAssistantSessionIdRoute
}

const ChatAssistantRouteChildren: ChatAssistantRouteChildren = {
  ChatAssistantSessionIdRoute: ChatAssistantSessionIdRoute,
}

const ChatAssistantRouteWithChildren = ChatAssistantRoute._addFileChildren(
  ChatAssistantRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatAssistantRoute: ChatAssistantRouteWithChildren,
  DocumentsRoute: DocumentsRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiTrpcChatSplatRoute: ApiTrpcChatSplatRoute,
  ApiTrpcIngestSplatRoute: ApiTrpcIngestSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
