/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { getRouter } from './router.tsx';
import type { startInstance } from './start.ts';
import { Route as rootRouteImport } from './routes/__root';
import { Route as ApiHealthRouteImport } from './routes/api/health';
import { Route as ChatAssistantRouteImport } from './routes/chat-assistant';
import { Route as ChatAssistantSessionIdRouteImport } from './routes/chat-assistant.$sessionId';
import { Route as DocumentsRouteImport } from './routes/documents';
import { Route as IndexRouteImport } from './routes/index';

const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any);
const ChatAssistantRoute = ChatAssistantRouteImport.update({
  id: '/chat-assistant',
  path: '/chat-assistant',
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);
const ChatAssistantSessionIdRoute = ChatAssistantSessionIdRouteImport.update({
  id: '/$sessionId',
  path: '/$sessionId',
  getParentRoute: () => ChatAssistantRoute,
} as any);
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/chat-assistant': typeof ChatAssistantRouteWithChildren;
  '/documents': typeof DocumentsRoute;
  '/api/health': typeof ApiHealthRoute;
  '/chat-assistant/$sessionId': typeof ChatAssistantSessionIdRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/chat-assistant': typeof ChatAssistantRouteWithChildren;
  '/documents': typeof DocumentsRoute;
  '/api/health': typeof ApiHealthRoute;
  '/chat-assistant/$sessionId': typeof ChatAssistantSessionIdRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/chat-assistant': typeof ChatAssistantRouteWithChildren;
  '/documents': typeof DocumentsRoute;
  '/api/health': typeof ApiHealthRoute;
  '/chat-assistant/$sessionId': typeof ChatAssistantSessionIdRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/chat-assistant'
    | '/documents'
    | '/api/health'
    | '/chat-assistant/$sessionId';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/'
    | '/chat-assistant'
    | '/documents'
    | '/api/health'
    | '/chat-assistant/$sessionId';
  id:
    | '__root__'
    | '/'
    | '/chat-assistant'
    | '/documents'
    | '/api/health'
    | '/chat-assistant/$sessionId';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  ChatAssistantRoute: typeof ChatAssistantRouteWithChildren;
  DocumentsRoute: typeof DocumentsRoute;
  ApiHealthRoute: typeof ApiHealthRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/documents': {
      id: '/documents';
      path: '/documents';
      fullPath: '/documents';
      preLoaderRoute: typeof DocumentsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/chat-assistant': {
      id: '/chat-assistant';
      path: '/chat-assistant';
      fullPath: '/chat-assistant';
      preLoaderRoute: typeof ChatAssistantRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/chat-assistant/$sessionId': {
      id: '/chat-assistant/$sessionId';
      path: '/$sessionId';
      fullPath: '/chat-assistant/$sessionId';
      preLoaderRoute: typeof ChatAssistantSessionIdRouteImport;
      parentRoute: typeof ChatAssistantRoute;
    };
    '/api/health': {
      id: '/api/health';
      path: '/api/health';
      fullPath: '/api/health';
      preLoaderRoute: typeof ApiHealthRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

interface ChatAssistantRouteChildren {
  ChatAssistantSessionIdRoute: typeof ChatAssistantSessionIdRoute;
}

const ChatAssistantRouteChildren: ChatAssistantRouteChildren = {
  ChatAssistantSessionIdRoute: ChatAssistantSessionIdRoute,
};

const ChatAssistantRouteWithChildren = ChatAssistantRoute._addFileChildren(
  ChatAssistantRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatAssistantRoute: ChatAssistantRouteWithChildren,
  DocumentsRoute: DocumentsRoute,
  ApiHealthRoute: ApiHealthRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

declare module '@tanstack/react-start' {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
    config: Awaited<ReturnType<typeof startInstance.getOptions>>;
  }
}
