/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ChatAssistantRouteImport } from './routes/chat-assistant'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StripeSuccessRouteImport } from './routes/stripe.success'
import { Route as SignUpSplatRouteImport } from './routes/sign-up.$'
import { Route as SignInSplatRouteImport } from './routes/sign-in.$'
import { Route as ApiStripeRouteImport } from './routes/api/stripe'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiTrpcIngestSplatRouteImport } from './routes/api/trpc/ingest.$'
import { Route as ApiTrpcChatSplatRouteImport } from './routes/api/trpc/chat.$'
import { Route as ApiTrpcBillingSplatRouteImport } from './routes/api/trpc/billing.$'

const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatAssistantRoute = ChatAssistantRouteImport.update({
  id: '/chat-assistant',
  path: '/chat-assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StripeSuccessRoute = StripeSuccessRouteImport.update({
  id: '/stripe/success',
  path: '/stripe/success',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpSplatRoute = SignUpSplatRouteImport.update({
  id: '/sign-up/$',
  path: '/sign-up/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeRoute = ApiStripeRouteImport.update({
  id: '/api/stripe',
  path: '/api/stripe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrpcIngestSplatRoute = ApiTrpcIngestSplatRouteImport.update({
  id: '/api/trpc/ingest/$',
  path: '/api/trpc/ingest/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrpcChatSplatRoute = ApiTrpcChatSplatRouteImport.update({
  id: '/api/trpc/chat/$',
  path: '/api/trpc/chat/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrpcBillingSplatRoute = ApiTrpcBillingSplatRouteImport.update({
  id: '/api/trpc/billing/$',
  path: '/api/trpc/billing/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/chat-assistant': typeof ChatAssistantRoute
  '/pricing': typeof PricingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/api/health': typeof ApiHealthRoute
  '/api/stripe': typeof ApiStripeRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/stripe/success': typeof StripeSuccessRoute
  '/api/trpc/billing/$': typeof ApiTrpcBillingSplatRoute
  '/api/trpc/chat/$': typeof ApiTrpcChatSplatRoute
  '/api/trpc/ingest/$': typeof ApiTrpcIngestSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/chat-assistant': typeof ChatAssistantRoute
  '/pricing': typeof PricingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/api/health': typeof ApiHealthRoute
  '/api/stripe': typeof ApiStripeRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/stripe/success': typeof StripeSuccessRoute
  '/api/trpc/billing/$': typeof ApiTrpcBillingSplatRoute
  '/api/trpc/chat/$': typeof ApiTrpcChatSplatRoute
  '/api/trpc/ingest/$': typeof ApiTrpcIngestSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/chat-assistant': typeof ChatAssistantRoute
  '/pricing': typeof PricingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/api/health': typeof ApiHealthRoute
  '/api/stripe': typeof ApiStripeRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/stripe/success': typeof StripeSuccessRoute
  '/api/trpc/billing/$': typeof ApiTrpcBillingSplatRoute
  '/api/trpc/chat/$': typeof ApiTrpcChatSplatRoute
  '/api/trpc/ingest/$': typeof ApiTrpcIngestSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/chat-assistant'
    | '/pricing'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/api/health'
    | '/api/stripe'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/stripe/success'
    | '/api/trpc/billing/$'
    | '/api/trpc/chat/$'
    | '/api/trpc/ingest/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/chat-assistant'
    | '/pricing'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/api/health'
    | '/api/stripe'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/stripe/success'
    | '/api/trpc/billing/$'
    | '/api/trpc/chat/$'
    | '/api/trpc/ingest/$'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/chat-assistant'
    | '/pricing'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/api/health'
    | '/api/stripe'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/stripe/success'
    | '/api/trpc/billing/$'
    | '/api/trpc/chat/$'
    | '/api/trpc/ingest/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ChatAssistantRoute: typeof ChatAssistantRoute
  PricingRoute: typeof PricingRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiStripeRoute: typeof ApiStripeRoute
  SignInSplatRoute: typeof SignInSplatRoute
  SignUpSplatRoute: typeof SignUpSplatRoute
  StripeSuccessRoute: typeof StripeSuccessRoute
  ApiTrpcBillingSplatRoute: typeof ApiTrpcBillingSplatRoute
  ApiTrpcChatSplatRoute: typeof ApiTrpcChatSplatRoute
  ApiTrpcIngestSplatRoute: typeof ApiTrpcIngestSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat-assistant': {
      id: '/chat-assistant'
      path: '/chat-assistant'
      fullPath: '/chat-assistant'
      preLoaderRoute: typeof ChatAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stripe/success': {
      id: '/stripe/success'
      path: '/stripe/success'
      fullPath: '/stripe/success'
      preLoaderRoute: typeof StripeSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up/$': {
      id: '/sign-up/$'
      path: '/sign-up/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof SignUpSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe': {
      id: '/api/stripe'
      path: '/api/stripe'
      fullPath: '/api/stripe'
      preLoaderRoute: typeof ApiStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trpc/ingest/$': {
      id: '/api/trpc/ingest/$'
      path: '/api/trpc/ingest/$'
      fullPath: '/api/trpc/ingest/$'
      preLoaderRoute: typeof ApiTrpcIngestSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trpc/chat/$': {
      id: '/api/trpc/chat/$'
      path: '/api/trpc/chat/$'
      fullPath: '/api/trpc/chat/$'
      preLoaderRoute: typeof ApiTrpcChatSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trpc/billing/$': {
      id: '/api/trpc/billing/$'
      path: '/api/trpc/billing/$'
      fullPath: '/api/trpc/billing/$'
      preLoaderRoute: typeof ApiTrpcBillingSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ChatAssistantRoute: ChatAssistantRoute,
  PricingRoute: PricingRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiStripeRoute: ApiStripeRoute,
  SignInSplatRoute: SignInSplatRoute,
  SignUpSplatRoute: SignUpSplatRoute,
  StripeSuccessRoute: StripeSuccessRoute,
  ApiTrpcBillingSplatRoute: ApiTrpcBillingSplatRoute,
  ApiTrpcChatSplatRoute: ApiTrpcChatSplatRoute,
  ApiTrpcIngestSplatRoute: ApiTrpcIngestSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
