/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StripeSuccessRouteImport } from './routes/stripe.success'
import { Route as ChatAssistantChar123SessionIdChar125RouteImport } from './routes/chat-assistant.{-$sessionId}'
import { Route as ApiStripeRouteImport } from './routes/api/stripe'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as ApiTrpcNotificationsSplatRouteImport } from './routes/api/trpc/notifications.$'
import { Route as ApiTrpcIngestSplatRouteImport } from './routes/api/trpc/ingest.$'
import { Route as ApiTrpcFeedbackSplatRouteImport } from './routes/api/trpc/feedback.$'
import { Route as ApiTrpcChatSplatRouteImport } from './routes/api/trpc/chat.$'
import { Route as ApiTrpcBillingSplatRouteImport } from './routes/api/trpc/billing.$'

const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StripeSuccessRoute = StripeSuccessRouteImport.update({
  id: '/stripe/success',
  path: '/stripe/success',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatAssistantChar123SessionIdChar125Route =
  ChatAssistantChar123SessionIdChar125RouteImport.update({
    id: '/chat-assistant/{-$sessionId}',
    path: '/chat-assistant/{-$sessionId}',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiStripeRoute = ApiStripeRouteImport.update({
  id: '/api/stripe',
  path: '/api/stripe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrpcNotificationsSplatRoute =
  ApiTrpcNotificationsSplatRouteImport.update({
    id: '/api/trpc/notifications/$',
    path: '/api/trpc/notifications/$',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiTrpcIngestSplatRoute = ApiTrpcIngestSplatRouteImport.update({
  id: '/api/trpc/ingest/$',
  path: '/api/trpc/ingest/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrpcFeedbackSplatRoute = ApiTrpcFeedbackSplatRouteImport.update({
  id: '/api/trpc/feedback/$',
  path: '/api/trpc/feedback/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrpcChatSplatRoute = ApiTrpcChatSplatRouteImport.update({
  id: '/api/trpc/chat/$',
  path: '/api/trpc/chat/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrpcBillingSplatRoute = ApiTrpcBillingSplatRouteImport.update({
  id: '/api/trpc/billing/$',
  path: '/api/trpc/billing/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/pricing': typeof PricingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/api/health': typeof ApiHealthRoute
  '/api/stripe': typeof ApiStripeRoute
  '/chat-assistant/{-$sessionId}': typeof ChatAssistantChar123SessionIdChar125Route
  '/stripe/success': typeof StripeSuccessRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/billing/$': typeof ApiTrpcBillingSplatRoute
  '/api/trpc/chat/$': typeof ApiTrpcChatSplatRoute
  '/api/trpc/feedback/$': typeof ApiTrpcFeedbackSplatRoute
  '/api/trpc/ingest/$': typeof ApiTrpcIngestSplatRoute
  '/api/trpc/notifications/$': typeof ApiTrpcNotificationsSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/pricing': typeof PricingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/api/health': typeof ApiHealthRoute
  '/api/stripe': typeof ApiStripeRoute
  '/chat-assistant/{-$sessionId}': typeof ChatAssistantChar123SessionIdChar125Route
  '/stripe/success': typeof StripeSuccessRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/billing/$': typeof ApiTrpcBillingSplatRoute
  '/api/trpc/chat/$': typeof ApiTrpcChatSplatRoute
  '/api/trpc/feedback/$': typeof ApiTrpcFeedbackSplatRoute
  '/api/trpc/ingest/$': typeof ApiTrpcIngestSplatRoute
  '/api/trpc/notifications/$': typeof ApiTrpcNotificationsSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/pricing': typeof PricingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/api/health': typeof ApiHealthRoute
  '/api/stripe': typeof ApiStripeRoute
  '/chat-assistant/{-$sessionId}': typeof ChatAssistantChar123SessionIdChar125Route
  '/stripe/success': typeof StripeSuccessRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/billing/$': typeof ApiTrpcBillingSplatRoute
  '/api/trpc/chat/$': typeof ApiTrpcChatSplatRoute
  '/api/trpc/feedback/$': typeof ApiTrpcFeedbackSplatRoute
  '/api/trpc/ingest/$': typeof ApiTrpcIngestSplatRoute
  '/api/trpc/notifications/$': typeof ApiTrpcNotificationsSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/pricing'
    | '/privacy-policy'
    | '/sign-in'
    | '/sign-up'
    | '/terms-of-service'
    | '/api/health'
    | '/api/stripe'
    | '/chat-assistant/{-$sessionId}'
    | '/stripe/success'
    | '/api/auth/$'
    | '/api/trpc/billing/$'
    | '/api/trpc/chat/$'
    | '/api/trpc/feedback/$'
    | '/api/trpc/ingest/$'
    | '/api/trpc/notifications/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/pricing'
    | '/privacy-policy'
    | '/sign-in'
    | '/sign-up'
    | '/terms-of-service'
    | '/api/health'
    | '/api/stripe'
    | '/chat-assistant/{-$sessionId}'
    | '/stripe/success'
    | '/api/auth/$'
    | '/api/trpc/billing/$'
    | '/api/trpc/chat/$'
    | '/api/trpc/feedback/$'
    | '/api/trpc/ingest/$'
    | '/api/trpc/notifications/$'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/pricing'
    | '/privacy-policy'
    | '/sign-in'
    | '/sign-up'
    | '/terms-of-service'
    | '/api/health'
    | '/api/stripe'
    | '/chat-assistant/{-$sessionId}'
    | '/stripe/success'
    | '/api/auth/$'
    | '/api/trpc/billing/$'
    | '/api/trpc/chat/$'
    | '/api/trpc/feedback/$'
    | '/api/trpc/ingest/$'
    | '/api/trpc/notifications/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  PricingRoute: typeof PricingRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiStripeRoute: typeof ApiStripeRoute
  ChatAssistantChar123SessionIdChar125Route: typeof ChatAssistantChar123SessionIdChar125Route
  StripeSuccessRoute: typeof StripeSuccessRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTrpcBillingSplatRoute: typeof ApiTrpcBillingSplatRoute
  ApiTrpcChatSplatRoute: typeof ApiTrpcChatSplatRoute
  ApiTrpcFeedbackSplatRoute: typeof ApiTrpcFeedbackSplatRoute
  ApiTrpcIngestSplatRoute: typeof ApiTrpcIngestSplatRoute
  ApiTrpcNotificationsSplatRoute: typeof ApiTrpcNotificationsSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stripe/success': {
      id: '/stripe/success'
      path: '/stripe/success'
      fullPath: '/stripe/success'
      preLoaderRoute: typeof StripeSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat-assistant/{-$sessionId}': {
      id: '/chat-assistant/{-$sessionId}'
      path: '/chat-assistant/{-$sessionId}'
      fullPath: '/chat-assistant/{-$sessionId}'
      preLoaderRoute: typeof ChatAssistantChar123SessionIdChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe': {
      id: '/api/stripe'
      path: '/api/stripe'
      fullPath: '/api/stripe'
      preLoaderRoute: typeof ApiStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trpc/notifications/$': {
      id: '/api/trpc/notifications/$'
      path: '/api/trpc/notifications/$'
      fullPath: '/api/trpc/notifications/$'
      preLoaderRoute: typeof ApiTrpcNotificationsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trpc/ingest/$': {
      id: '/api/trpc/ingest/$'
      path: '/api/trpc/ingest/$'
      fullPath: '/api/trpc/ingest/$'
      preLoaderRoute: typeof ApiTrpcIngestSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trpc/feedback/$': {
      id: '/api/trpc/feedback/$'
      path: '/api/trpc/feedback/$'
      fullPath: '/api/trpc/feedback/$'
      preLoaderRoute: typeof ApiTrpcFeedbackSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trpc/chat/$': {
      id: '/api/trpc/chat/$'
      path: '/api/trpc/chat/$'
      fullPath: '/api/trpc/chat/$'
      preLoaderRoute: typeof ApiTrpcChatSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trpc/billing/$': {
      id: '/api/trpc/billing/$'
      path: '/api/trpc/billing/$'
      fullPath: '/api/trpc/billing/$'
      preLoaderRoute: typeof ApiTrpcBillingSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  PricingRoute: PricingRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiStripeRoute: ApiStripeRoute,
  ChatAssistantChar123SessionIdChar125Route:
    ChatAssistantChar123SessionIdChar125Route,
  StripeSuccessRoute: StripeSuccessRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTrpcBillingSplatRoute: ApiTrpcBillingSplatRoute,
  ApiTrpcChatSplatRoute: ApiTrpcChatSplatRoute,
  ApiTrpcFeedbackSplatRoute: ApiTrpcFeedbackSplatRoute,
  ApiTrpcIngestSplatRoute: ApiTrpcIngestSplatRoute,
  ApiTrpcNotificationsSplatRoute: ApiTrpcNotificationsSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
