#!/usr/bin/env bash
#
# extract-app.sh - Generate a standalone, single-app slice of this monorepo.
#
# Copies the repo (minus turbo/next/build caches and node_modules) into a temp
# dir, runs `turbo prune` there to keep only the target app's dependency subset,
# overlays the non-workspace tooling/config that prune drops (scripts, docs, ops,
# secrets, root dotfiles, etc.), then moves the result into out/<dir>.
#
# The result is a self-contained repo for a single app that installs and builds
# out of the box (`pnpm install`).
#
# Usage:
#   scripts/extract-app.sh [APP] [OUT_DIR]
#
#   APP      Workspace package to keep (default: @acme/nextjs)
#   OUT_DIR  Output dir under out/ (default: repo-copy)
#
# Examples:
#   scripts/extract-app.sh
#   scripts/extract-app.sh @acme/tanstack-start tanstack-copy

set -euo pipefail

APP="${1:-@acme/nextjs}"
OUT_NAME="${2:-repo-copy}"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
OUT_DIR="$REPO_ROOT/out/$OUT_NAME"

# Caches / generated dirs we never want to copy. node_modules and lockfile-derived
# state are regenerated by `pnpm install`; .git is dropped so the slice is a fresh
# tree; .claude holds regenerated skill symlinks.
RSYNC_EXCLUDES=(
  --exclude=node_modules/
  --exclude=.turbo/
  --exclude=.next/
  --exclude=.cache/
  --exclude=.git/
  --exclude=.claude/
  --exclude=/out/
)

log() { printf '\033[1;34m==>\033[0m %s\n' "$*"; }

command -v rsync >/dev/null 2>&1 || { echo "rsync is required" >&2; exit 1; }

TURBO_BIN="$REPO_ROOT/node_modules/.bin/turbo"
if [[ ! -x "$TURBO_BIN" ]]; then
  if command -v turbo >/dev/null 2>&1; then
    TURBO_BIN="$(command -v turbo)"
  else
    echo "turbo not found (run pnpm install first)" >&2
    exit 1
  fi
fi

WORK="$(mktemp -d "${TMPDIR:-/tmp}/extract-app.XXXXXX")"
cleanup() { rm -rf "$WORK"; }
trap cleanup EXIT

log "Copying repo into temp (excluding caches & node_modules)..."
rsync -a "${RSYNC_EXCLUDES[@]}" "$REPO_ROOT/" "$WORK/"

log "Pruning '$APP' dependency subset..."
PRUNED="$WORK/.pruned"
( cd "$WORK" && "$TURBO_BIN" prune "$APP" --out-dir "$PRUNED" >/dev/null )

log "Overlaying non-workspace tooling/config that prune dropped..."
# prune writes the pruned manifests, lockfile and the workspace subset (apps/,
# packages/, tooling/). Copy back every other top-level entry from the working
# copy that prune did NOT produce - scripts/, docs/, ops/, secrets/, .agents/,
# root dotfiles, etc. - without re-adding the packages prune deliberately
# stripped (those top-level dirs already exist in the pruned tree, so they are
# skipped).
shopt -s dotglob nullglob
for src in "$WORK"/*; do
  name="$(basename "$src")"
  [[ "$name" == ".pruned" ]] && continue
  [[ -e "$PRUNED/$name" ]] && continue
  cp -R "$src" "$PRUNED/$name"
done
shopt -u dotglob nullglob

log "Moving result into out/$OUT_NAME..."
rm -rf "$OUT_DIR"
mkdir -p "$REPO_ROOT/out"
mv "$PRUNED" "$OUT_DIR"

log "Done."
echo
echo "  Single-app slice for '$APP' -> out/$OUT_NAME"
echo "  Next:  cd out/$OUT_NAME && pnpm install && pnpm build:nextjs"
echo
