---
config:
  layout: elk
---
graph TD
	QHZT("@acme/admin#topo") --> ETTT("@acme/auth#topo")
	QHZT("@acme/admin#topo") --> JEGP("@acme/billing#topo")
	QHZT("@acme/admin#topo") --> LRHC("@acme/ingest#topo")
	QHZT("@acme/admin#topo") --> WCIN("@acme/ui#topo")
	JEGP("@acme/billing#topo") --> ETTT("@acme/auth#topo")
	JEGP("@acme/billing#topo") --> TPBW("@acme/hooks#topo")
	JEGP("@acme/billing#topo") --> WCIN("@acme/ui#topo")
	GVMR("@acme/chat#topo") --> TPBW("@acme/hooks#topo")
	GVMR("@acme/chat#topo") --> ITTZ("@acme/models#topo")
	GVMR("@acme/chat#topo") --> VXGS("@acme/rag#topo")
	GVMR("@acme/chat#topo") --> WCIN("@acme/ui#topo")
	NEPG("@acme/feedback#topo") --> TPBW("@acme/hooks#topo")
	NEPG("@acme/feedback#topo") --> ITTZ("@acme/models#topo")
	NEPG("@acme/feedback#topo") --> VXGS("@acme/rag#topo")
	NEPG("@acme/feedback#topo") --> WCIN("@acme/ui#topo")
	LRHC("@acme/ingest#topo") --> TPBW("@acme/hooks#topo")
	LRHC("@acme/ingest#topo") --> VXGS("@acme/rag#topo")
	LRHC("@acme/ingest#topo") --> WCIN("@acme/ui#topo")
	HVTJ("@acme/nextjs#topo") --> QHZT("@acme/admin#topo")
	HVTJ("@acme/nextjs#topo") --> ETTT("@acme/auth#topo")
	HVTJ("@acme/nextjs#topo") --> JEGP("@acme/billing#topo")
	HVTJ("@acme/nextjs#topo") --> GVMR("@acme/chat#topo")
	HVTJ("@acme/nextjs#topo") --> NEPG("@acme/feedback#topo")
	HVTJ("@acme/nextjs#topo") --> LRHC("@acme/ingest#topo")
	HVTJ("@acme/nextjs#topo") --> ITTZ("@acme/models#topo")
	HVTJ("@acme/nextjs#topo") --> VXGS("@acme/rag#topo")
	HVTJ("@acme/nextjs#topo") --> WCIN("@acme/ui#topo")
	SEOP("@acme/nextjs-slim#topo") --> GVMR("@acme/chat#topo")
	SEOP("@acme/nextjs-slim#topo") --> LRHC("@acme/ingest#topo")
	SEOP("@acme/nextjs-slim#topo") --> ITTZ("@acme/models#topo")
	SEOP("@acme/nextjs-slim#topo") --> VXGS("@acme/rag#topo")
	SEOP("@acme/nextjs-slim#topo") --> WCIN("@acme/ui#topo")
	VXGS("@acme/rag#topo") --> ITTZ("@acme/models#topo")
	FFQP("@acme/sidebar#topo") --> ETTT("@acme/auth#topo")
	FFQP("@acme/sidebar#topo") --> JEGP("@acme/billing#topo")
	FFQP("@acme/sidebar#topo") --> WCIN("@acme/ui#topo")
	KUWX("@acme/tanstack-slim#topo") --> GVMR("@acme/chat#topo")
	KUWX("@acme/tanstack-slim#topo") --> LRHC("@acme/ingest#topo")
	KUWX("@acme/tanstack-slim#topo") --> ITTZ("@acme/models#topo")
	KUWX("@acme/tanstack-slim#topo") --> VXGS("@acme/rag#topo")
	KUWX("@acme/tanstack-slim#topo") --> WCIN("@acme/ui#topo")
	WZGG("@acme/tanstack-start#topo") --> QHZT("@acme/admin#topo")
	WZGG("@acme/tanstack-start#topo") --> ETTT("@acme/auth#topo")
	WZGG("@acme/tanstack-start#topo") --> JEGP("@acme/billing#topo")
	WZGG("@acme/tanstack-start#topo") --> GVMR("@acme/chat#topo")
	WZGG("@acme/tanstack-start#topo") --> NEPG("@acme/feedback#topo")
	WZGG("@acme/tanstack-start#topo") --> LRHC("@acme/ingest#topo")
	WZGG("@acme/tanstack-start#topo") --> ITTZ("@acme/models#topo")
	WZGG("@acme/tanstack-start#topo") --> VXGS("@acme/rag#topo")
	WZGG("@acme/tanstack-start#topo") --> WCIN("@acme/ui#topo")
