---
config:
  layout: elk
---
graph TD
	QHZT("@acme/admin#topo") --> ETTT("@acme/auth#topo")
	QHZT("@acme/admin#topo") --> JEGP("@acme/billing#topo")
	QHZT("@acme/admin#topo") --> LRHC("@acme/ingest#topo")
	QHZT("@acme/admin#topo") --> WCIN("@acme/ui#topo")
	JEGP("@acme/billing#topo") --> ETTT("@acme/auth#topo")
	JEGP("@acme/billing#topo") --> TPBW("@acme/hooks#topo")
	JEGP("@acme/billing#topo") --> WCIN("@acme/ui#topo")
	GVMR("@acme/chat#topo") --> TPBW("@acme/hooks#topo")
	GVMR("@acme/chat#topo") --> ITTZ("@acme/models#topo")
	GVMR("@acme/chat#topo") --> VXGS("@acme/rag#topo")
	GVMR("@acme/chat#topo") --> WCIN("@acme/ui#topo")
	LRHC("@acme/ingest#topo") --> TPBW("@acme/hooks#topo")
	LRHC("@acme/ingest#topo") --> VXGS("@acme/rag#topo")
	LRHC("@acme/ingest#topo") --> WCIN("@acme/ui#topo")
	WJGP("@acme/nextjs#topo") --> QHZT("@acme/admin#topo")
	WJGP("@acme/nextjs#topo") --> ETTT("@acme/auth#topo")
	WJGP("@acme/nextjs#topo") --> JEGP("@acme/billing#topo")
	WJGP("@acme/nextjs#topo") --> GVMR("@acme/chat#topo")
	WJGP("@acme/nextjs#topo") --> LRHC("@acme/ingest#topo")
	WJGP("@acme/nextjs#topo") --> ITTZ("@acme/models#topo")
	WJGP("@acme/nextjs#topo") --> VXGS("@acme/rag#topo")
	WJGP("@acme/nextjs#topo") --> USYV("@acme/sidebar#topo")
	WJGP("@acme/nextjs#topo") --> WCIN("@acme/ui#topo")
	VXGS("@acme/rag#topo") --> ITTZ("@acme/models#topo")
	USYV("@acme/sidebar#topo") --> ETTT("@acme/auth#topo")
	USYV("@acme/sidebar#topo") --> JEGP("@acme/billing#topo")
	USYV("@acme/sidebar#topo") --> WCIN("@acme/ui#topo")
	SYNO("@acme/tanstack-start#topo") --> QHZT("@acme/admin#topo")
	SYNO("@acme/tanstack-start#topo") --> ETTT("@acme/auth#topo")
	SYNO("@acme/tanstack-start#topo") --> JEGP("@acme/billing#topo")
	SYNO("@acme/tanstack-start#topo") --> GVMR("@acme/chat#topo")
	SYNO("@acme/tanstack-start#topo") --> LRHC("@acme/ingest#topo")
	SYNO("@acme/tanstack-start#topo") --> WCIN("@acme/ui#topo")
