#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=8

# Not `.env`: `pnpm lint` and `pnpm typecheck` never go through `pnpm with-env`,
# so turbo's three variables have to be in the shell itself. This file is what
# the shell profile sources, and what gives this wizard its re-run defaults.
ENV_FILE=".turbo-cache.env"

REPO_ROOT="$(git rev-parse --show-toplevel)"
cd "$REPO_ROOT"

banner "Shared turbo cache — Cloudflare Worker + R2"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Prerequisites"
say "This wizard deploys a turbo remote cache you own, then points both this"
say "laptop and CI at it. Nothing here touches Vercel."
printf '\n'
say "You need: a Cloudflare account (free tier is enough) and the gh CLI."
printf '\n'

MISSING=0
for tool in git node gh curl; do
  if command -v "$tool" >/dev/null 2>&1; then
    note "✓ $tool"
  else
    warn "missing: $tool"
    MISSING=1
  fi
done
if gh auth status >/dev/null 2>&1; then
  note "✓ gh is authenticated"
else
  warn "gh is not authenticated — run 'gh auth login' first, or the CI variables get skipped"
fi
[[ "$MISSING" -eq 0 ]] || { printf '\n'; warn "install the missing tools, then re-run."; exit 1; }
printf '\n'
pause "All set?"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Get the worker source"
say "The cache server is its own project — it does not live in this repo. We"
say "clone it somewhere alongside, deploy from there, and never touch it again"
say "unless you want to upgrade it."
printf '\n'
ask WORKER_DIR "Where should it live? [../turborepo-remote-cache-cloudflare]"
[[ -n "$WORKER_DIR" ]] || WORKER_DIR="../turborepo-remote-cache-cloudflare"
write_env WORKER_DIR "$WORKER_DIR"

if [[ -d "$WORKER_DIR/.git" ]]; then
  note "already cloned at $WORKER_DIR"
else
  step "Cloning AdiRishi/turborepo-remote-cache-cloudflare"
  git clone --depth 1 https://github.com/AdiRishi/turborepo-remote-cache-cloudflare.git "$WORKER_DIR"
fi
step "Installing its dependencies (this brings in wrangler)"
(cd "$WORKER_DIR" && pnpm install)
printf '\n'
pause "Worker source ready?"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Log in to Cloudflare"
say "wrangler will open a browser and ask you to authorise it. Only you can do"
say "this part — approve it in the page that opens, then come back here."
printf '\n'
if (cd "$WORKER_DIR" && pnpm wrangler whoami 2>/dev/null | grep -qi 'account'); then
  note "already logged in:"
  (cd "$WORKER_DIR" && pnpm wrangler whoami 2>/dev/null | sed 's/^/    /') || true
else
  (cd "$WORKER_DIR" && pnpm wrangler login)
fi
printf '\n'
pause "Logged in?"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Create the R2 bucket"
say "The worker's wrangler.jsonc binds R2_STORE to a bucket named"
say "'turborepo-cache'. Keep that name unless you also edit that file."
printf '\n'
note "R2 gives 10GB free and charges nothing for egress."
note "The worker expires artifacts after 720h, swept by a daily 03:00 cron."
printf '\n'
if confirm "Create the R2 bucket 'turborepo-cache' now?"; then
  (cd "$WORKER_DIR" && pnpm wrangler r2 bucket create turborepo-cache) || \
    warn "bucket create failed — if it already exists, that is fine; otherwise fix and re-run"
else
  SKIPPED+=("R2 bucket 'turborepo-cache' (wrangler r2 bucket create turborepo-cache)")
fi
printf '\n'
pause "Bucket ready?"

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Deploy the worker"
say "This publishes the cache server to your Cloudflare account and prints the"
say "URL it is reachable at."
printf '\n'
if confirm "Deploy now?"; then
  (cd "$WORKER_DIR" && pnpm run deploy) || warn "deploy failed — read the error above before continuing"
else
  SKIPPED+=("worker deploy (pnpm run deploy in $WORKER_DIR)")
fi
printf '\n'
say "Look for a line like:"
note "  https://turborepo-remote-cache.<your-subdomain>.workers.dev"
printf '\n'
ask TURBO_API "Paste that URL (no trailing slash):"
TURBO_API="${TURBO_API%/}"
[[ "$TURBO_API" =~ ^https:// ]] || warn "that does not look like an https URL — the cache will not work"
write_env TURBO_API "$TURBO_API"

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Set the cache token"
say "One bearer token guards the cache. The worker checks it; your laptop and"
say "CI present it. It is not a Cloudflare credential — you choose it."
printf '\n'
GENERATED=""
if command -v openssl >/dev/null 2>&1; then
  GENERATED="$(openssl rand -hex 32)"
  say "Generated one for you:"
  printf '    %s%s%s\n' "$BOLD" "$GENERATED" "$RESET"
  printf '\n'
fi
if [[ -n "$GENERATED" ]] && confirm "Use the generated token?"; then
  TURBO_TOKEN="$GENERATED"
else
  ask_secret TURBO_TOKEN "Paste the token you want to use:"
fi
[[ -n "$TURBO_TOKEN" ]] || { warn "a token is required"; exit 1; }
write_env TURBO_TOKEN "$TURBO_TOKEN"

step "Uploading it to the worker as its TURBO_TOKEN secret"
if printf '%s' "$TURBO_TOKEN" | (cd "$WORKER_DIR" && pnpm wrangler secret put TURBO_TOKEN); then
  note "✓ the worker now requires this token"
else
  warn "could not set the worker secret"
  SKIPPED+=("worker secret (echo \$TURBO_TOKEN | pnpm wrangler secret put TURBO_TOKEN)")
fi
printf '\n'
pause "Token in place?"

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Wire this repo"
say "Three values reach CI. TURBO_TEAM is the one to be careful about: the"
say "worker keys every object as <team>/<hash>, so if CI and this laptop"
say "disagree they silently use separate namespaces and never share a hit."
printf '\n'
say "It is captured once here and written to both places, so they cannot drift."
printf '\n'
DEFAULT_TEAM="$(basename "$REPO_ROOT")"
ask TURBO_TEAM "Team namespace [$DEFAULT_TEAM]:"
[[ -n "$TURBO_TEAM" ]] || TURBO_TEAM="$DEFAULT_TEAM"
write_env TURBO_TEAM "$TURBO_TEAM"
printf '\n'
set_var TURBO_API "$TURBO_API"
set_var TURBO_TEAM "$TURBO_TEAM"
set_secret TURBO_TOKEN "$TURBO_TOKEN"
printf '\n'
pause "CI wired?"

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "Point this laptop at it, and verify"
say "turbo reads these from the environment, and 'pnpm lint' does not load any"
say ".env — so they belong in your shell profile."
printf '\n'
PROFILE_LINE="set -a; . \"$REPO_ROOT/$ENV_FILE\"; set +a"
say "Add this line to your shell profile:"
printf '    %s%s%s\n' "$BOLD" "$PROFILE_LINE" "$RESET"
printf '\n'

SHELL_PROFILE=""
case "${SHELL:-}" in
*/zsh) SHELL_PROFILE="$HOME/.zshrc" ;;
*/bash) SHELL_PROFILE="$HOME/.bashrc" ;;
esac

if [[ -n "$SHELL_PROFILE" ]]; then
  if [[ -f "$SHELL_PROFILE" ]] && grep -qF "$ENV_FILE" "$SHELL_PROFILE"; then
    note "already present in $SHELL_PROFILE"
  elif confirm "Append it to $SHELL_PROFILE for you?"; then
    {
      printf '\n# Shared turbo remote cache (scripts/wizards/turbo-cache-setup.sh)\n'
      printf '%s\n' "$PROFILE_LINE"
    } >> "$SHELL_PROFILE"
    note "✓ appended to $SHELL_PROFILE"
  else
    SKIPPED+=("shell profile line (add it to $SHELL_PROFILE by hand)")
  fi
else
  SKIPPED+=("shell profile line (add it to your profile by hand)")
fi

printf '\n'
step "Checking the cache answers and accepts the token"
if TURBO_API="$TURBO_API" TURBO_TOKEN="$TURBO_TOKEN" TURBO_TEAM="$TURBO_TEAM" \
  bash "$REPO_ROOT/scripts/check-remote-cache.sh"; then
  printf '  %s✓ the shared cache is live and authenticating%s\n' "$GREEN" "$RESET"
else
  warn "the check failed — read its output above"
  SKIPPED+=("a passing scripts/check-remote-cache.sh")
fi
printf '\n'
say "Open a new shell, then confirm CI agrees by pushing a branch."
printf '\n'
pause "Done?"

finish
