#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES
#
# Walks one bank resync end to end: pin, sync, merge, hand the vendor branch
# over, reinstall, verify. Every stage asks what state it is already in before
# it does anything, so a half-finished resync can be resumed by re-running —
# including one where the merge is already committed or already pushed.
#
# The stage that cannot be automated is the merge: resolving a three-way
# conflict is a judgement call about which side is right. The wizard stops
# there, waits, and carries on when the tree is clean.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=10

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
cd "$ROOT"

MANIFEST="bank.manifest.json"
BANK_LIB="tooling/bank/src/lib/bank.mjs"

# Run a command without letting a non-zero exit abort the wizard. Every git and
# pnpm call below goes through this: a merge that conflicts and a sync that
# reports drift both exit non-zero by design, and neither is a wizard failure.
run() {
  printf '  %s$ %s%s\n' "$DIM" "$*" "$RESET"
  set +e
  "$@"
  local rc=$?
  set -e
  return $rc
}

# The vendor branch name the bank tool *in this working tree* will use. Read
# from the source rather than hardcoded, because the whole point of this stage
# is that the name has changed across versions: whichever copy of the tool is
# checked out right now is the one whose name has to exist.
tool_vendor_branch() {
  local name=""
  [[ -f "$BANK_LIB" ]] &&
    name=$(sed -n "s/^export const VENDOR_BRANCH = '\([^']*\)'.*/\1/p" "$BANK_LIB" | head -n1)
  printf '%s' "${name:-vendor/bank}"
}

have_branch() { git show-ref --verify --quiet "refs/heads/$1"; }
vendor_branches() { git for-each-ref --format='%(refname:short)' 'refs/heads/vendor/*'; }
merging() { git rev-parse -q --verify MERGE_HEAD >/dev/null 2>&1; }
conflicts() { git diff --name-only --diff-filter=U; }
# One string field out of the manifest. Deliberately sed rather than node: this
# runs in a tree that may not have installed yet, and against a manifest whose
# only fields it needs are flat strings.
manifest_field() {
  sed -n "s/.*\"$1\"[[:space:]]*:[[:space:]]*\"\([^\"]*\)\".*/\1/p" "$MANIFEST" | head -n1
}

# Move the accumulated vendor history onto the name the current tool expects.
# The branch is the merge base — the only record of what the bank last gave
# you — so a rename is always right where a fresh orphan is always wrong.
adopt_vendor_name() {
  local want="$1" others found=""
  have_branch "$want" && return 0
  others=$(vendor_branches | grep -v "^${want}$" || true)
  [[ -z "$others" ]] && return 1
  found=$(printf '%s\n' "$others" | head -n1)
  warn "the bank tool here uses '$want', but your history is on '$found'."
  say "That branch is your merge base. Renaming keeps it; leaving it strands it,"
  say "and the next sync builds a parentless branch that conflicts on every file."
  if confirm "Rename '$found' to '$want'?"; then
    run git branch -m "$found" "$want"
    return 0
  fi
  return 1
}

banner "Bank resync"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Preflight"
if [[ ! -f "$MANIFEST" ]]; then
  warn "no $MANIFEST here — this repo does not subscribe to a bank."
  note "Run 'pnpm setup:wizard' to author one, then come back."
  exit 1
fi
say "upstream:  $(manifest_field upstream)"
say "ref:       $(manifest_field ref)"
say "branch:    $(git rev-parse --abbrev-ref HEAD)"
say "vendor:    $(vendor_branches | tr '\n' ' ')"
printf '\n'

DEFAULT_BRANCH=$(git symbolic-ref -q --short refs/remotes/origin/HEAD 2>/dev/null | sed 's|^origin/||')
DEFAULT_BRANCH=${DEFAULT_BRANCH:-main}
if [[ "$(git rev-parse --abbrev-ref HEAD)" == "$DEFAULT_BRANCH" ]]; then
  warn "you are on '$DEFAULT_BRANCH'. A resync is a reviewable change, not a hotfix."
  if confirm "Create a branch for it?"; then
    run git switch -c "bank/resync-$(date +%F)"
  fi
fi

if ! merging && [[ -n "$(git status --porcelain)" ]]; then
  warn "the working tree is dirty. A merge on top of unrelated edits is hard to read."
  confirm "Continue anyway?" || exit 1
fi
pause

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Pin the ref"
CURRENT_REF=$(manifest_field ref)
say "Currently pinned to: $CURRENT_REF"
printf '\n'
note "A tag is a fixed point you chose. A branch takes its tip on every sync —"
note "no edit per bump, but '--check' can no longer say how far behind you are,"
note "because the pinned ref and the upstream tip become the same commit."
printf '\n'
if merging; then
  note "A merge is already in progress, so the ref is settled for this run."
else
  printf '  %sNew ref (Enter keeps %s):%s ' "$BOLD" "$CURRENT_REF" "$RESET"
  read -r NEW_REF || true
  if [[ -n "${NEW_REF:-}" && "$NEW_REF" != "$CURRENT_REF" ]]; then
    MANIFEST_TMP=$(mktemp)
    sed "s|\(\"ref\"[[:space:]]*:[[:space:]]*\)\"[^\"]*\"|\1\"$NEW_REF\"|" \
      "$MANIFEST" >"$MANIFEST_TMP" && mv "$MANIFEST_TMP" "$MANIFEST"
    printf '  %s✓ pinned%s %s\n' "$GREEN" "$RESET" "$NEW_REF"
  fi
fi
pause

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Vendor branch — before the sync"
VENDOR=$(tool_vendor_branch)
say "The bank tool in this tree writes to: $VENDOR"
if have_branch "$VENDOR"; then
  printf '  %s✓%s '"$VENDOR"' is here — the merge base is intact.\n' "$GREEN" "$RESET"
elif adopt_vendor_name "$VENDOR"; then
  printf '  %s✓%s history moved onto %s.\n' "$GREEN" "$RESET" "$VENDOR"
elif [[ -z "$(vendor_branches)" ]]; then
  note "No vendor branch yet — this repo has never synced. The first one is a"
  note "genuine unrelated-histories merge, and that is the only time it is."
else
  warn "continuing without the rename. Expect a merge with no common ancestor."
fi
pause

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "What the bump would bring"
if merging; then
  note "Skipped — a merge is already in progress."
else
  run pnpm bank:sync --check || true
fi
printf '\n'
pause

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Sync"
if merging; then
  note "Skipped — a merge is already in progress."
else
  say "Rebuilds $VENDOR from the bank at the pinned ref. Nothing enters your"
  say "own history: the sync never merges."
  printf '\n'
  if ! run pnpm bank:sync; then
    warn "the sync failed. Read the error above — a bad ref or a selection that no"
    warn "longer resolves upstream are the usual two. Nothing has been written."
    exit 1
  fi
fi
pause

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Preview what arrived"
if ! have_branch "$VENDOR"; then
  warn "no $VENDOR branch — nothing to preview."
elif git rev-parse -q --verify "${VENDOR}^" >/dev/null 2>&1; then
  say "Changed since your last sync — this is what the merge will apply:"
  printf '\n'
  run git --no-pager diff --stat "${VENDOR}^" "$VENDOR" || true
  printf '\n'
  note "Back out any time before merging: git branch -f $VENDOR ${VENDOR}^"
else
  warn "$VENDOR has no parent commit — it is an orphan."
  say "If this repo has synced before, the merge base has been stranded and every"
  say "file will conflict as an add/add. Stop, put the history back on this name,"
  say "and re-run — do not reach for --allow-unrelated-histories."
  confirm "Continue anyway?" || exit 1
fi
pause

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Merge — your part"
if ! merging && have_branch "$VENDOR" && git merge-base --is-ancestor "$VENDOR" HEAD 2>/dev/null; then
  printf '  %s✓%s already merged — %s is an ancestor of HEAD.\n' "$GREEN" "$RESET" "$VENDOR"
elif ! merging; then
  say "Merging $VENDOR into $(git rev-parse --abbrev-ref HEAD)."
  printf '\n'
  MERGE_LOG=$(mktemp)
  if run git merge --no-edit "$VENDOR" >"$MERGE_LOG" 2>&1; then
    cat "$MERGE_LOG"
    printf '  %s✓%s merged clean.\n' "$GREEN" "$RESET"
  else
    cat "$MERGE_LOG"
    if grep -q "unrelated histories" "$MERGE_LOG"; then
      printf '\n'
      warn "git refuses: no common ancestor. That is the symptom, not the step."
      say "The vendor branch holding your base is under another name, or was deleted."
      say "Put it back and re-run. Passing --allow-unrelated-histories here turns a"
      say "handful of real conflicts into every file, resolved by hand."
      rm -f "$MERGE_LOG"
      exit 1
    fi
  fi
  rm -f "$MERGE_LOG"
fi

while merging && [[ -n "$(conflicts)" ]]; do
  printf '\n'
  warn "$(conflicts | wc -l | tr -d ' ') file(s) still conflicted:"
  conflicts | sed 's/^/    /'
  printf '\n'
  note "Resolve them in your editor, 'git add' each one, then come back here."
  note "Take the bank's side for upstream fixes; keep yours where you meant it."
  printf '\n'
  if confirm "Abandon this merge instead (git merge --abort)?"; then
    run git merge --abort || true
    warn "merge aborted. Nothing has changed. Re-run when you are ready."
    exit 1
  fi
  pause "Press Enter to re-check"
done

if merging; then
  printf '  %s✓%s every conflict resolved.\n' "$GREEN" "$RESET"
  if confirm "Commit the merge?"; then
    run git commit --no-edit || true
  else
    warn "leaving the merge uncommitted — re-run when you want to finish it."
    exit 1
  fi
fi
pause

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "Vendor branch — after the merge"
WANTED=$(tool_vendor_branch)
if [[ "$WANTED" != "$VENDOR" ]]; then
  say "The merge brought a bank tool that writes to '$WANTED' instead of '$VENDOR'."
  say "Handing the history over now is what keeps your next sync a three-way merge."
  adopt_vendor_name "$WANTED" || warn "not renamed — your next sync will build an orphan."
  VENDOR="$WANTED"
else
  printf '  %s✓%s still %s — nothing to hand over.\n' "$GREEN" "$RESET" "$VENDOR"
fi
printf '\n'

if have_branch "$VENDOR"; then
  if git ls-remote --exit-code --heads origin "$VENDOR" >/dev/null 2>&1 &&
     [[ "$(git rev-parse "$VENDOR")" == "$(git rev-parse "origin/$VENDOR" 2>/dev/null || echo none)" ]]; then
    printf '  %s✓%s %s is already pushed and current.\n' "$GREEN" "$RESET" "$VENDOR"
  else
    say "$VENDOR is state you cannot reconstruct. Unpushed, it exists on this"
    say "machine only — a fresh clone syncs into an orphan and replays all of this."
    if confirm "Push $VENDOR to origin?"; then
      run git push -u origin "$VENDOR" || warn "push failed — do it by hand before you forget."
    else
      SKIPPED+=("push $VENDOR to origin")
    fi
  fi
fi
pause

# ── 9 ─────────────────────────────────────────────────────────────────────
stage "Reinstall"
say "The merge moved manifests, patches and the workspace file, so the lockfile"
say "and node_modules are behind until this runs."
printf '\n'
if confirm "Run pnpm install?"; then
  run pnpm install || warn "install failed — resolve it before running the gates."
else
  SKIPPED+=("pnpm install")
fi
pause

# ── 10 ────────────────────────────────────────────────────────────────────
stage "Verify"
say "Auto-fix first, then the read-only gate."
printf '\n'
note "A bump can bring gates this repo has never run. Anything they report is"
note "content that was already non-conforming, surfaced rather than caused."
printf '\n'
if confirm "Run pnpm tidy?"; then
  run pnpm tidy || warn "tidy reported problems — read them above."
else
  SKIPPED+=("pnpm tidy")
fi
printf '\n'
if confirm "Run pnpm quality-gate? (slow)"; then
  run pnpm quality-gate || warn "the gate failed — logs/quality-gate.log names the stage."
else
  SKIPPED+=("pnpm quality-gate")
fi
printf '\n'
note "Still yours to do: commit the tidy, push the branch, open the pull request."

finish
